### ISSUE TITLE
Booking Index Limit

### ISSUE THREAD

**Issue by emmar** [Checkfront/API#25]
I have successfully retrieved bookings from `api/3.0/booking/index`, but I am not getting all of the bookings.  I noticed that there is a "limit" parameter (see http://api.checkfront.com/ref/booking/index.html?highlight=limit), with a default of 100.  Is there any way to just get all bookings?

**Comment by Nebual** [comment]
?limit does default to 100, though you may raise it up to 250. Beyond that, you will need to make multiple requests utilizing ?page, and then combine the results in your client.
`/api/3.0/booking/index?limit=250&page=1`
`/api/3.0/booking/index?limit=250&page=2` retrieves bookings 251-500
etc.
You can find the total number of pages in `$response['request']['pages']`, and the total number of bookings in `$response['request']['total_records']`.

**Comment by emmar** [comment]
Thanks for the quick response and for answering the question I did not ask, namely how many records there are to retrieve.  I will be able to use that info to get all records.  That solution is workable.  Thanks!
