### ISSUE TITLE
Having trouble with webhook

### ISSUE THREAD

**Issue by sheideman** [Checkfront/API#30]
Is there a way to see booking parameters on a webhook post for booking status change?

**Comment by jaymichls** [comment]
Hi @sheideman, 

Thanks for the question. Do you have an example of what you mean by booking parameters? 
I'd love to hear more about what information you're trying to receive from the booking webhook.  

If you don't see the properties you're looking for contained in this sample response: http://api.checkfront.com/ref/webhook/booking.html#sample-booking-notification
A good option could be using the webhook as a trigger to make a subsequent call.

**Comment by gegere** [comment]
@sheideman looking to review the data sent from Checkfront before written out a bunch of code? Try using a webhook parsing service, I have been using https://webhook.site along with a few others to model the data I'd like to use. (example webhook data below)

When a booking status changes it sounds like you would like to review the items node and compare between old and new.

https://gist.github.com/gegere/8b839037b54131565391e3cfe7e0990c

**Comment by sheideman** [comment]
Thanks guys! @gegere  I actually used webhook.site to see the JSON structure, that is how I knew I couldn't see the params for the items.  I was able to just do an API call on the individual booking to bring back all the data I need so I am good to go! 👍 I am closing. Appreciate the quick replies.
