### ISSUE TITLE
Get more booking details

### ISSUE THREAD

**Issue by APIIntegrationIndia** [Checkfront/API#36]
Dear Team,

In Get More Booking Details API, i am getting list of items in this API. Now the problem is list of items is not coming in an array. I am shocked to know this that list of items is not coming in an array. Can you please look into this and speeden this up? This issue is causing my create my workflow on Zapier. 

A brief about me - I help business integrate apps that they use on platform like Zapier, Workato, etc. I am integrating your API's with some other software of your customer.

**Comment by APIIntegrationIndia** [comment]
Also, Do you have previous version API which i can test and see if i can build Zapier workflow with previous version API?

**Comment by JayCoughlan** [comment]
Hi APIIntegrationIndia,

Thank you for reaching out. This Github repo is specifically for comments and questions regarding the API documentation. For questions or requests regarding the API itself, please reach out to the Checkfront support team at code@checkfront.com.

Warm wishes,

Jay Coughlan | Checkfront Technical Support Analyst
